### ISSUE TITLE
Persist flag docker example in readme not working 

### ISSUE THREAD

**Issue by erikzeneco** [pikami/cosmium#2]
#### Summary
nothing is persisted when using `-e Persist=save.json`

#### Steps to reproduce
Run docker example from readme:
```
docker run --rm \
  -e Persist=/save.json \
  -v ./save.json:/save.json \
  -p 8081:8081 \
  ghcr.io/pikami/cosmium

```
#### Expected behavior
contents are persisted

#### Observed behavior (that appears unintentional)
nothing is persisted

#### Possible fixes
https://github.com/pikami/cosmium/pull/1

For environment variable flags use envPrefix and capitalization flags as described later in readme

**Comment by pikami** [comment]
README.md was updated with instructions to use environment variable `COSMIUM_PERSIST`, closing.
