### ISSUE TITLE
Support patch operation "set"

### ISSUE THREAD

**Issue by compulim** [pikami/cosmium#7]
#### Summary

https://learn.microsoft.com/en-us/azure/cosmos-db/partial-document-update

The patch operation in CosmoDB supports a few more operations than [JSON Patch (RFC-6902)](https://tools.ietf.org/html/rfc6902), such as "set".

#### Steps to reproduce

```ts
container
  .item('some-id', 'some-id')
  .patch({
    operations: [
      { op: 'set', path: '/some-array/0', value: 'Hello, World!' }
    ]
  });
```

#### Expected behavior

It should not throw "invalid operation" error.

#### Observed behavior (that appears unintentional)

It throws "invalid operation" error.

#### Possible fixes

May need to extend the JSON Patch library, use another one, or intercept the call and perform the work manually.

**Comment by pikami** [comment]
Thanks for reporting, I've added support for 'set' and 'incr' operations.
This will be included in v0.1.12 release
