### ISSUE TITLE
Support parameter in bracket

### ISSUE THREAD

**Issue by compulim** [pikami/cosmium#8]
#### Summary

When using a parameter in bracket, it returns no result despite there should be.

#### Steps to reproduce

Given the database contains:

```json
[
  {
    "id": "some-id",
    "bag": {
      "one": 1
    }
  }
]
```

When running query with parameter (`@name`) and use it in bracket notation:

```ts
const jsonQueryResponse = await container.items
  .query({
    parameters: [
      { name: '@name', value: 'one' },
      { name: '@value', value: 1 }
    ],
    query: 'SELECT * FROM c WHERE c.bag[@name] = @value'
  })
  .fetchNext();
```

#### Expected behavior

It should return the document.

Verified it is working in real-world CosmosDB.

#### Observed behavior (that appears unintentional)

It does not return any documents (empty array).

#### Possible fixes

If the parameter is inlined in the `query`, it works.

```diff
  const jsonQueryResponse = await container.items
    .query({
      parameters: [
-       { name: '@name', value: 'one' },
        { name: '@value', value: 1 }
      ],
-     query: 'SELECT * FROM c WHERE c.bag[@name] = @value'
+     query: 'SELECT * FROM c WHERE c.bag["one"] = @value'
    })
    .fetchNext();
```

**Comment by pikami** [comment]
Thanks for the heads up, should be fixed now

**Comment by compulim** [comment]
Thanks for quick response and love your hard work.

I understand it's never designed to become a true clone. I try not to ask for crazy things. 🤣

After trying the official emulator which is [previewing support of M1 and Surface Pro 11](https://learn.microsoft.com/en-us/azure/cosmos-db/emulator-linux) since Build 2024, I still enjoy your version of emulator and will stay here for a number of reasons:

- Docker image of the official emulator > 2 GB, impractical for CI use
- `EXISTS` is not supported in official emulator
   - Bracket notation is not supported either 😜
- cosmium is very fast to boot, very small footprint, intuitive to use, very practical for CI and RPi

TBH, it seems the official emulator is not targeting itself as a true clone, cosmium have a lot of opportunities to become the better choice.

Keep up the good work. ❤️❤️

p.s. I am not a Go developer, I can't self-serve fixing bugs and building new features. 🙇🏻‍♂️

**Comment by pikami** [comment]
I try my best to make cosmium as close to CosmosDB as possible, but I know I can miss things or mess up sometimes. Hearing about how you’re using it (and enjoying it!) gives me even more motivation to keep improving it.

I’m honestly super happy with how the project’s turned out so far. Keeping it lightweight and easy to use has always been my goal, and it’s great to know that’s working for you.

It’s awesome to see people actually trying cosmium and finding it useful—it really keeps me excited to keep going.

Thanks again for your feedback! ❤️
